### PR TITLE
Fix bugs and Rework Converters

### PR DESCRIPTION
**Pull request by BenDol**
- Cleaned up the code base to be more readable (fitting common Java standards)
- Fixed an NPE in PlatformSpecificGwt#fillSpecificDataAdapter
- ValuePropertyAdapter will now check != null whatever object it receives.
- Reworked the Converters to work more efficiently.

There is a bit of a problem with type safety in this library, might need some work to get it more robust in many different use cases. I will look into it when I have more time.

### CODE REVIEW

**Comment by BenDol** [comment]
Since this repository isn't being maintained I have [forked and rewrote](https://github.com/BenDol/Databind) the binding library to be more lightweight, since using this library mean't +600kb to my initial page load (and growing fast).

So far I have replaced the ClassInfo Generators with apt processors and removed method support to trim down the code size, this library will only offer direct field support until I have time to write a controlled way to reflect methods for GWT compilation (without massive code increase).

Observable system, also doubled the code, having to create another class for each POJO model required on the client. Basically I only want it for one way binding since that is the most useful requirement for me. This would need to be more controllable in the future to avoid massive code increase.

**Comment by ltearno** [comment]
Hi Ben, yes this library is still maintained ! Just that i didnt have time
to look deeply at your pull request, because it seems to me that you
introduced some fundamental changes, so i wanted to be sure if i wanted to
merge it or not...

I see in your repo that you changed all fqns to your company's one and that
you re-licensed the source with your company also. I don't think that's
it's cool or a practice that is considered constructive in the open source
community. My project is MIT licensed so i don't know if you can claim
ownership and re-license it under Apache, i will check...

But i understand from your previous email that your requirements are
different from the ones that motivated the hexa binding library. So you
might write up a completely new library from scratch !

Arnaud

**Comment by BenDol** [comment]
I have rewritten majority of the code already, at least 70% of the sources. Also I didn't see any license information so I wasn't sure what it was licensed under. My intention is not to steal your sources, just using them as a base foundation for a new project from scratch. If the license change is an issue I will change it to the MIT license. So I would say it is constructive for the open source community and not just copy and paste antics.

Edit: Forgot to mention that I will also reference you/your company as the owner of any sources that have not changed substantially.

**Comment by BenDol** [comment]
Check https://github.com/BenDol/Databind/tree/bd_rewrite for my rewrite changes so far (a lot more to come).

**Pull request closed without merging**
