### PR TITLE
Rewrote the ObservableAnnotationProcessor again, complete reformat & ClazzBundleGenerator fixes.

### PR DESCRIPTION
**Pull request by BenDol**
Wasn't completely happy with the way it was before.
- Better abstraction implementation,
- Easier workflow format with cleaner code,
- Fixed the issue with default constructors,
- Added optional copyConstructor annotation option.
- Fixed some bugs here and there,
- Made some of the type checking more robust for example to field/method access.
- Added a few tests for some possible breaks.
- Fixed issues with static, final and abstract methods/fields.
- ClazzBundleGenerator will now bundle all classes from each ClazzBundle.
  - This will fix a number of issues I was having in SuperDevMode.
  - Also removes client specific glue code causing Exceptions on the server.

``` java
    // Causes server side exceptions since GWT.create is a client call.
    static
    {
        GWT.<ClassBundle>create( ClassBundle.class ).register();
    }
```
- Moved the following packages:

``` java
fr.lteconsulting.hexa.databinding.gwt
fr.lteconsulting.hexa.databinding.propertyadapters.gwt
fr.lteconsulting.hexa.databinding.watchablecollection.gwt
```

into:

``` java
fr.lteconsulting.hexa.databinding.gwt*
```
- Added a new ObservableGenerator gwt generator, this will create you a deferred Observable object when given the source objects type in GWT.create. I have this working with Gwt-Jackson using a @JsonCreator to return a deferred Observable object (i.e. GWT.create is invoked or you could simply have it pass a new instance of the generated object).

Should be pretty stable now! (Keep an eye out for any issues).
http://youtu.be/chkep16dN-I

### CODE REVIEW

**Comment by BenDol** [comment]
@ltearno would you be able to review this? I want to make the GWT package structure a bit more coherent and can't do it until this has been merged.

I want to make the packages like so:

```
fr.lteconsulting.hexa.databinding.gwt*
```

Right now its really hard to work with

```
fr.lteconsulting.hexa.databinding.gwt
fr.lteconsulting.hexa.databinding.propertyadapters.gwt
fr.lteconsulting.hexa.databinding.watchablecollection.gwt
```

Or perhaps there is a good reason for this?

**Comment by BenDol** [comment]
@ltearno Able to review this PR? Thanks!

**Comment by ltearno** [comment]
Hi Ben, sorry i am actually on holidays... Can this wait until next monday
? I'll try to find time to validate your PR before monday, but not sure if
i'll be able...
Thanks

**Comment by BenDol** [comment]
Ah okay no problem, it can wait.

**Comment by ltearno** [comment]
Well done man !
Just a note about the fqn changes. I have no problem with that if you feel better with the new layout. I just had in mind that Hexa Binding could also work on Android and JavaFX so the "gwt" in the package name was just a suffix.
But again, i am also happy with the change you made...

Thanks

**Pull request merged**
